[tool.poetry]
name = "payop-python"
version = "0.0.1"
description = "Payop python unofficial package"
authors = ["Roman Melnyk <roman.melnyk20071992@gmail.com>"]

readme = "README.md"

[tool.poetry.dependencies]
requests = "^2"
